accounts/urls.py
from django.conf.urls import url

from accounts.views import SignUp, login_view,login_user, logout_view,dashboard_view


app_name = "accounts"

urlpatterns = [
    url(r'^register/$', SignUp.as_view(), name="signup"),
    url(r'^login/$', login_view, name="login"),
    url(r'^login_user/$', login_user, name="login_user"),
    url(r'^logout/$', logout_view, name="logout_view"),
    url(r'^dashboard/(?P<username>[\w.@+-]+)/$', dashboard_view, name="home"),
]

app/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static

from app.main_view import Home


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', Home.as_view(), name="home"),
    url(r'account/', include('accounts.urls', namespace="accounts")),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save

# Create your models here.


class Member(models.Model):

    def __str__(self):
        return self.user.username

    def get_absolute_url(self):
        from django.core.urlresolvers import reverse
        return reverse('home', kwargs={'pk': self.pk})

    user =models.OneToOneField(User,related_name="member", on_delete=models.CASCADE)
  


def create_member(sender,**kwargs):
    if kwargs['created']:
        member = Member.objects.create(user=kwargs['instance'])

post_save.connect(create_member, sender=User)

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

from accounts.models import Member

from django import forms

class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control','name': 'username'}))
    password = forms.CharField(widget=forms.PasswordInput(
                                attrs={'class': 'form-control','name': 'password'}))
    honeypot = forms.CharField(required=False,widget=forms.HiddenInput,label="Leave empty")


    def clean_honeypot(self):
        honeypot = self.cleaned_data['honeypot']
        if len(honeypot):
            raise forms.ValidationError("honeypot should be left empty")

    def clean_username(self):
        username = self.cleaned_data['username']
        if len(username) == 0:
            raise forms.ValidationError("Invalid username or password")

    def clean_password(self):
        password = self.cleaned_data['password']
        if len(password) == 0:
            raise forms.ValidationError("Invalid username or password")



class UserSignUpForm(UserCreationForm):
    class Meta():
        fields = ('username','first_name','last_name','email','password1','password2')
        model = get_user_model()

    def __init__(self, *args, **kwargs):
        super(UserSignUpForm, self).__init__(*args, **kwargs)

        self.fields['username'].label = 'username'
        self.fields['first_name'].label = 'first name'
        self.fields['last_name'].label = 'last name'
        self.fields['email'].label = 'email'
        self.fields['password1'].label = 'password'
        self.fields['password1'].label = 'Confirm password'

        self.fields['username'].widget = forms.TextInput(attrs= {
            'placeholder':'username',
            'class':'form-control'
        })

        self.fields['first_name'].widget = forms.TextInput(attrs= {
            'placeholder':'first name',
            'class':'form-control'
        })

        self.fields['last_name'].widget = forms.TextInput(attrs= {
            'placeholder':'last name',
            'class':'form-control'
        })

        self.fields['email'].widget = forms.EmailInput(attrs= {
            'placeholder':'email address',
            'class':'form-control'
        })

        self.fields['password1'].widget = forms.PasswordInput(attrs= {
            'placeholder':'password',
            'class':'form-control'
        })

        self.fields['password2'].widget = forms.PasswordInput(attrs= {
            'placeholder':'confirm password',
            'class':'form-control'
        })

accounts/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth import authenticate, login, logout


from django.views.generic import CreateView,UpdateView,ListView, UpdateView
from django.contrib.auth.models import User
from django.urls import reverse_lazy

from accounts.forms import UserSignUpForm, LoginForm

from accounts.models import Member


# Create your views here.
class SignUp(CreateView):
    form_class = UserSignUpForm
    success_url = reverse_lazy('accounts:login')
    template_name = 'accounts/signup.html'


def login_view(request):
    form = LoginForm()

    if request.user.is_authenticated:
        return redirect("home")
    return render(request, 'accounts/login.html', {'form':form})


def login_user(request):
    form = LoginForm(request.POST or None)
    print(form.data)
    if request.method == "POST" and form.is_valid() :       
        username = form.data['username']
        password = form.data['password']
        
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect("home")
        else:
            form = LoginForm()
            return render(request, "accounts/login.html", {"form":form,"error":"Invalid username or password"})
    return render(request, "accounts/login.html")

    if request.method == "GET":
        return redirect("home")



def logout_view(request):
    logout(request)
    return redirect("accounts:login")


def dashboard_view(request, username):
    if request.method == "POST":
        return HttpResponse(status=500)

    if request.method == "GET":
        user = request.user
    
    if not user.is_authenticated:
        return redirect('accounts:login')
    

    return render(request, 'accounts/dashboard.html')

accounts/templates/accounts/dashboard.html
{% extends 'base.html' %}

{% block title %}
Create free account and enjoy 
{% endblock %}

{% block content %}
<div class="container">
   
          <div class="jumbotron">
              welcome {{user.username}}
          </div>

    </div>
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block title %}
Create free account and enjoy 
{% endblock %}

{% block content %}
<div class="container mb-5"> 
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-6">
            <h1>Login</h1>
            <form class="" method="POST" enctype="multipart/form-data" action="{% url 'accounts:login_user' %}">
                {% if error %}
                <span>{{error}}</span>
                {% endif %}
                    {% csrf_token %}
                    {{form}}                      
                <input type="submit" class="btn btn-lg my-3 text-light" style="background:#262626" value="Login">
            </form>
    
        </div>
        <div class="col-md-3"></div>
    </div>         
</div>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block title %}
Create free account and enjoy 
{% endblock %}

{% block content %}
<div class="container">
        <div class="row">
            <div class="col col-md-8 offset-md-2">
     
                    <h1>Create a free account</h1>
                    <form method="POST" class="mb-3" enctype="multipart/form-data">
                            {% csrf_token %}
                           
                            {{form.errors}}
                            
                            <div class="form-row">
                                <div class="col-md-6 mb-3">
                                    <label for="username">username</label>
                                    {{form.username}}                     
                                </div>

                                <div class="col-md-6 mb-3">
                                    <label for="first_name">first name</label>
                                    {{form.first_name}}                     
                                </div>

                            </div>

                            <div class="form-row">
                                <div class="col-md-6 mb-3">
                                    <label for="last_name">last name</label>
                                    {{form.last_name}}                     
                                </div>

                                <div class="col-md-6 mb-3">
                                    <label for="email">email</label>
                                    {{form.email}}                     
                                </div>

                            </div>

                            <div class="form-row">
                                <div class="col-md-6 mb-3">
                                    <label for="password1">password</label>
                                    {{form.password1}}                     
                                </div>

                                <div class="col-md-6 mb-3">
                                    <label for="password2">confirm password</label>
                                    {{form.password2}}                     
                                </div>

                            </div>
                          
                        <input type="submit" class="btn btn-primary" value="Create Account">
                    </form>
             
            </div>
        </div>
    </div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}welcome{% endblock %}</title>

    <script
    src="https://code.jquery.com/jquery-3.3.1.min.js"
    integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
    crossorigin="anonymous"></script>

    <!-- bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" 
          integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" 
          crossorigin="anonymous">

    <!-- fontawsome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" 
          integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" 
          crossorigin="anonymous">
</head>
<body>
        <!-- nav -->
        <nav class="navbar navbar-expand-lg navbar-light bg-light  header-top">
            <a href="{% url 'home' %}" class="navbar-brand">
                Home
            </a>
            <button class="navbar-toggler bg-light" type="button" data-toggle="collapse" data-target="#ourGameshopNavbar" aria-controls="ourGameshopNavbar" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <ul class="navbar-nav d-flex flex-row justify-content-between container">
                
                {% if user.is_authenticated %}
                <li>
                    <a class="nav-link" href="{% url 'accounts:logout_view' %}">Logout</a>
                </li>
                
            
                {% else %}
                <li>
                    <a class="dropdown-item" href="{% url 'accounts:login' %}">Login</a>
                </li>
                
                <li>
                    <a class="dropdown-item" href="{% url 'accounts:signup' %}">Signup</a>
                </li>
                
                {% endif %} 
                

        
                {% if user.is_authenticated %}
                <li>
                    <a class="dropdown-item" href="{% url 'accounts:home' username=user.username %}">Dashboard</a>
                </li>  
                {% endif %} 
    
            </ul>
              
           
        </nav>
        <!-- nav ends -->
    {% block content %}
    {% endblock %}
</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="jumbotron">
        {% if user.is_authenticated %}
        <h1>Welcome home</h1>
        {% else %}
        <h1>You are not authenticated.</h1>
        {% endif %}
    </div>
</div>
{% endblock %}